// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async restRequest(req: ApiRequest) : Promise<Result<ApiResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rest_request", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restCancelRequest(cancelKey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rest_cancel_request", { cancelKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch a raw URL and return the response body as a string.
 * Used by the ImportModal to download remote OpenAPI specs via Rust
 * instead of a browser fetch() call.
 */
async fetchUrl(url: string) : Promise<Result<FetchUrlResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_url", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDockBadge(label: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_dock_badge", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Establish a new WebSocket connection.
 * 
 * - Spawns a background task that owns the socket and forwards incoming frames
 * as Tauri events (`ws://message/<connection_id>`).
 * - Returns synchronously once the HTTP upgrade handshake completes (or fails).
 * - A channel sender is stored in `registry` so `ws_send` / `ws_disconnect`
 * can reach the background task.
 */
async wsConnect(req: WsConnectRequest) : Promise<Result<WsConnectResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ws_connect", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a text or binary frame to an existing WebSocket connection.
 */
async wsSend(req: WsSendRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ws_send", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Close an active WebSocket connection.
 */
async wsDisconnect(connectionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ws_disconnect", { connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch and return a GraphQL server's introspection schema.
 * 
 * This runs the full introspection query via the Rust/curl stack so the
 * frontend never makes a direct network request.
 */
async graphqlIntrospect(req: GraphQLIntrospectRequest) : Promise<Result<GraphQLIntrospectResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("graphql_introspect", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sioConnect(req: SioConnectRequest) : Promise<Result<SioConnectResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sio_connect", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sioEmit(req: SioEmitRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sio_emit", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sioEmitWithAck(req: SioEmitAckRequest) : Promise<Result<SioEmitAckResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sio_emit_with_ack", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sioDisconnect(connectionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sio_disconnect", { connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mqttConnect(req: MqttConnectRequest) : Promise<Result<MqttConnectResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mqtt_connect", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mqttPublish(req: MqttPublishRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mqtt_publish", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mqttSubscribe(req: MqttSubscribeRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mqtt_subscribe", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mqttUnsubscribe(req: MqttUnsubscribeRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mqtt_unsubscribe", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mqttDisconnect(connectionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mqtt_disconnect", { connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ApiKeyLocation = "Header" | "Query"
export type ApiRequest = { method: Methods; url: string; headers: Partial<{ [key in string]: string }>; body: BodyType; auth: AuthType; query_params: Partial<{ [key in string]: string }>; cookies: Cookie[]; timeout_ms: number | null; follow_redirects: boolean | null; max_redirects: number | null; verify_ssl: boolean | null; proxy: ProxyConfig | null; protocol: HttpProtocol | null; 
/**
 * Tab / request name for background completion notifications (REST only).
 */
request_label?: string | null; 
/**
 * When set, `rest_cancel_request` can abort this transfer (libcurl progress hook).
 */
cancel_key?: string | null }
export type ApiResponse = { status: number; status_text: string; headers: Partial<{ [key in string]: string }>; cookies: Cookie[]; body_base64: string; timing: TimingInfo; request_size: SizeInfo; response_size: SizeInfo; redirects: RedirectEntry[]; remote_addr: string | null; http_version: string; available_renderers: ResponseRenderer[]; detected_content_type: string | null; protocol_used: string; error: string | null }
export type AuthType = "None" | { Basic: { username: string; password: string } } | { Bearer: { token: string } } | { ApiKey: { key: string; value: string; add_to: ApiKeyLocation } }
export type BodyType = "None" | { Raw: { content: string; content_type: string | null } } | { FormUrlEncoded: { fields: Partial<{ [key in string]: string }> } } | { Multipart: { fields: MultipartField[] } } | { Binary: { data: number[]; filename: string | null } }
export type Cookie = { name: string; value: string; domain: string | null; path: string | null; expires: string | null; http_only: boolean | null; secure: boolean | null }
/**
 * Response from a raw URL GET fetch (used by ImportModal for OpenAPI URLs).
 */
export type FetchUrlResponse = { status: number; body: string }
/**
 * Request to fetch (introspect) a GraphQL schema.
 */
export type GraphQLIntrospectRequest = { url: string; headers: Partial<{ [key in string]: string }>; 
/**
 * GraphQL file name for background completion notifications.
 */
request_label?: string | null }
/**
 * Result of a GraphQL introspection fetch.
 */
export type GraphQLIntrospectResponse = { 
/**
 * Raw introspection JSON (the `data` field from the response).
 */
schema_json: string | null; error: string | null }
export type HttpProtocol = "Tcp"
export type Methods = "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "HEAD" | "OPTIONS" | "TRACE" | "CONNECT"
export type MqttConnectRequest = { connection_id: string; url: string; client_id: string; username: string | null; password: string | null; clean_session: boolean | null; keep_alive_secs: number | null; subscriptions: MqttSubscription[] }
export type MqttConnectResponse = { connection_id: string; url: string; client_id: string; error: string | null }
export type MqttDisconnectedEvent = { connection_id: string; reason: string }
export type MqttIncomingMessage = { connection_id: string; id: string; topic: string; data: string; qos: number; retain: boolean; timestamp_ms: number }
export type MqttPublishRequest = { connection_id: string; topic: string; data: string; qos: number; retain: boolean | null }
export type MqttSubscribeRequest = { connection_id: string; topic: string; qos: number }
export type MqttSubscription = { topic: string; qos: number }
export type MqttUnsubscribeRequest = { connection_id: string; topic: string }
export type MultipartField = { name: string; value: MultipartValue }
export type MultipartValue = { Text: string } | { File: { data: number[]; filename: string; content_type: string | null } }
export type ProxyConfig = { url: string; username: string | null; password: string | null }
export type RedirectEntry = { url: string; status: number }
export type ResponseRenderer = "Raw" | "Json" | "Xml" | "Html" | "HtmlPreview" | "Image" | "Audio" | "Video" | "Pdf"
/**
 * Sent from the frontend to open a new Socket.IO connection.
 */
export type SioConnectRequest = { 
/**
 * Unique connection ID chosen by the caller.
 */
connection_id: string; 
/**
 * The Socket.IO server URL (http:// or https://).
 */
url: string; 
/**
 * Optional namespace to connect to (defaults to "/").
 */
namespace: string | null; 
/**
 * Optional extra headers.
 */
headers: Partial<{ [key in string]: string }>; 
/**
 * Optional auth payload sent during the handshake.
 */
auth: string | null; 
/**
 * Transport selection.
 */
transport: string | null; 
/**
 * Whether automatic reconnects are enabled.
 */
reconnect: boolean | null; 
/**
 * Whether to reconnect after an explicit server disconnect.
 */
reconnect_on_disconnect: boolean | null; 
/**
 * Minimum reconnect delay in milliseconds.
 */
reconnect_delay_min_ms: number | null; 
/**
 * Maximum reconnect delay in milliseconds.
 */
reconnect_delay_max_ms: number | null; 
/**
 * Max reconnect attempts. Null means library default/infinite depending on client behavior.
 */
max_reconnect_attempts: number | null }
/**
 * Response returned from `sio_connect`.
 */
export type SioConnectResponse = { connection_id: string; url: string; namespace: string; error: string | null }
/**
 * Pushed as a Tauri event when the connection is closed.
 */
export type SioDisconnectedEvent = { connection_id: string; reason: string }
/**
 * Sent from the frontend to emit an event and await an ack payload.
 */
export type SioEmitAckRequest = { connection_id: string; event: string; data: string; timeout_ms: number }
/**
 * Result returned from an ack-aware emit.
 */
export type SioEmitAckResponse = { event: string; data: string; timed_out: boolean }
/**
 * Sent from the frontend to emit an event.
 */
export type SioEmitRequest = { connection_id: string; event: string; data: string }
/**
 * Pushed as a Tauri event for every message received.
 */
export type SioIncomingMessage = { connection_id: string; id: string; event: string; data: string; timestamp_ms: number }
export type SizeInfo = { headers_bytes: number; body_bytes: number; total_bytes: number }
export type TimingInfo = { total_ms: number; dns_lookup_ms: number; tcp_handshake_ms: number; tls_handshake_ms: number; transfer_start_ms: number; ttfb_ms: number; content_download_ms: number }
/**
 * Pushed as a Tauri event (`ws://closed/<connection_id>`) when the connection
 * is terminated (either side).
 */
export type WsClosedEvent = { connection_id: string; code: number; reason: string }
/**
 * Sent from the frontend to open a new WebSocket connection.
 */
export type WsConnectRequest = { 
/**
 * Unique connection ID chosen by the caller (e.g. the WebSocketFile id).
 */
connection_id: string; 
/**
 * The WebSocket URL to connect to (ws:// or wss://).
 */
url: string; 
/**
 * Optional extra headers to include in the upgrade handshake.
 */
headers: Partial<{ [key in string]: string }>; 
/**
 * Optional sub-protocols.
 */
protocols: string[] }
/**
 * Response returned synchronously from `ws_connect`.
 */
export type WsConnectResponse = { connection_id: string; 
/**
 * The exact URL that was dialled after query-param expansion.
 */
url: string; 
/**
 * HTTP status of the upgrade response (101 on success).
 */
status_code: number; status_text: string; 
/**
 * Response headers from the HTTP upgrade handshake.
 */
response_headers: Partial<{ [key in string]: string }>; error: string | null }
/**
 * Pushed as a Tauri event (`ws://message/<connection_id>`) for every frame
 * the server sends after the connection is established.
 */
export type WsIncomingMessage = { connection_id: string; id: string; data: string; binary: boolean; timestamp_ms: number }
/**
 * Sent from the frontend to `ws_send` to push a frame to the server.
 */
export type WsSendRequest = { connection_id: string; data: string; binary: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
