// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async restRequest(req: ApiRequest): Promise<Result<ApiResponse, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("rest_request", { req }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
};

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type ApiKeyLocation = "Header" | "Query";
export type ApiRequest = {
  method: Methods;
  url: string;
  headers: Partial<{ [key in string]: string }>;
  body: BodyType;
  auth: AuthType;
  query_params: Partial<{ [key in string]: string }>;
  cookies: Cookie[];
  timeout_ms: number | null;
  follow_redirects: boolean | null;
  max_redirects: number | null;
  verify_ssl: boolean | null;
  proxy: ProxyConfig | null;
  protocol: HttpProtocol | null;
};
export type ApiResponse = {
  status: number;
  status_text: string;
  headers: Partial<{ [key in string]: string }>;
  cookies: Cookie[];
  body_base64: string;
  timing: TimingInfo;
  request_size: SizeInfo;
  response_size: SizeInfo;
  redirects: RedirectEntry[];
  remote_addr: string | null;
  http_version: string;
  available_renderers: ResponseRenderer[];
  detected_content_type: string | null;
  protocol_used: string;
  error: string | null;
};
export type AuthType =
  | "None"
  | { Basic: { username: string; password: string } }
  | { Bearer: { token: string } }
  | { ApiKey: { key: string; value: string; add_to: ApiKeyLocation } };
export type BodyType =
  | "None"
  | { Raw: { content: string; content_type: string | null } }
  | { FormUrlEncoded: { fields: Partial<{ [key in string]: string }> } }
  | { Multipart: { fields: MultipartField[] } }
  | { Binary: { data: number[]; filename: string | null } };
export type Cookie = {
  name: string;
  value: string;
  domain: string | null;
  path: string | null;
  expires: string | null;
  http_only: boolean | null;
  secure: boolean | null;
};
export type HttpProtocol = "Tcp" | "Quic";
export type Methods =
  | "GET"
  | "POST"
  | "PUT"
  | "DELETE"
  | "PATCH"
  | "HEAD"
  | "OPTIONS"
  | "TRACE"
  | "CONNECT";
export type MultipartField = { name: string; value: MultipartValue };
export type MultipartValue =
  | { Text: string }
  | { File: { data: number[]; filename: string; content_type: string | null } };
export type ProxyConfig = {
  url: string;
  username: string | null;
  password: string | null;
};
export type RedirectEntry = { url: string; status: number };
export type ResponseRenderer =
  | "Raw"
  | "Json"
  | "Xml"
  | "Html"
  | "HtmlPreview"
  | "Image"
  | "Audio"
  | "Video"
  | "Pdf";
export type SizeInfo = {
  headers_bytes: number;
  body_bytes: number;
  total_bytes: number;
};
export type TimingInfo = {
  total_ms: number;
  dns_lookup_ms: number;
  tcp_handshake_ms: number;
  tls_handshake_ms: number;
  transfer_start_ms: number;
  ttfb_ms: number;
  content_download_ms: number;
};

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>,
) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>;
      };
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T];

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case "listen":
                return (arg: any) => TAURI_API_EVENT.listen(name, arg);
              case "once":
                return (arg: any) => TAURI_API_EVENT.once(name, arg);
              case "emit":
                return (arg: any) => TAURI_API_EVENT.emit(name, arg);
            }
          },
        });
      },
    },
  );
}
